# Generated by Django 4.1.2 on 2022-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
